---
title: "Cameroon Peace Promotion Project"
author: "Christopher D. Grady & Rebecca Chapman"
date: \today
output:
  word_document:
    toc: yes
  pdf_document:
    number_sections: yes
    toc: yes
  html_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Scan in Workspace/load libraries
load("cp3_report_dat.Rdata")
library(mosaic)
library(survey)
library(lmtest)
library(sandwich)
library(stats)
library(ggplot2)
library(reshape2)
```

# Overview

# Social Contact

```{r sc}
plot.fun(outcome='sc.index',dat=svy,title='Social Contact Index by Group')
```

# Cultural Understanding

```{r cultural}
plot.fun(outcome='cult.index',dat=svy,title='Cultural Understanding Index by Group')
```

# Support for Women's Empowerment

Higher scores good.

```{r cultural}
plot.fun(outcome='wom.index',dat=svy,title="Women's Empowerment Index by Group")

plot.fun(outcome='form.Attitudes.women_money',dat=svy,
         title="Women Should Have a Say in How Her Household Spends Money")
plot.fun(outcome='form.Attitudes.women_work_children_suffer',dat=svy,
         title="Women Work Children Suffer")
plot.fun(outcome='form.Attitudes.boy_edu_better',dat=svy,
         title="Education Boys Better")
plot.fun(outcome='form.Attitudes.early_marriage_good',dat=svy,
         title="Early Marriage Good")
```

# Religious Tolerance

Higher scores good.

```{r tol}
plot.fun(outcome='reltol.index',dat=svy,title='Religious Tolerance Index by Group')

plot.fun(outcome='form.Attitudes.one_valid_interpret',dat=svy,
         title='More than One Valid Interpretation of Religious Teaching')
plot.fun(outcome='form.Attitudes.my_rel_promotes_peace',dat=svy,
         title='My Religion Promotes Peace')
plot.fun(outcome='form.Attitudes.other_rel_promte_peace',dat=svy,
         title='Other Religions Promote Peace')
plot.fun(outcome='form.Attitudes.dif_ppl_live_peace',dat=svy,
         title='People of Different Religions Live Peacefully')

```


# Violence

Higher scores good, lower scores bad.

```{r tol}
plot.fun(outcome='vio.index',dat=svy,title='Violence Index by Group')
```


# Youth